version: '3'
services:
 postgres:
  image: postgres:14.1
  environment:
   POSTGRES_PASSWORD : postgres 
  ports:
  - 5432:5432
 postgres_admin:
  image: dpage/pgadmin4
  ports:
  - 80:80
  environment:
  - PGADMIN_DEFAULT_EMAIL:admin@admin.com
  - PGADMIN_DEFAULT_PASSWORD:postgres